export const SET_ERRORS = "SET_ERRORS";

// customer options
export const TOGGLE_CUSTOMER_LOADING = "TOGGLE_CUSTOMER_LOADING";
export const TOGGLE_CUSTOMERS_LOADING = "TOGGLE_CUSTOMERS_LOADING";
export const SET_CURRENT_CUSTOMER = "SET_CURRENT_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const LIST_CUSTOMERS = "LIST_CUSTOMERS";

export const TOGGLE_ADDRESS_LOADING = "TOGGLE_ADDRESSES_LOADING";
export const SET_PROVINCES = "SET_PROVINCES";
export const SET_DISTRICTS = "SET_DISTRICTS";
export const SET_COMMUNES = "SET_COMMUNES";
export const SET_CURRENT_LIST_ADDRESS = "SET_CURRENT_LIST_ADDRESS";
export const SET_DEFAULT_ADDRESS = "SET_DEFAULT_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
// customer options
export const TOGGLE_ADMIN_LOADING = "TOGGLE_ADMIN_LOADING";
export const TOGGLE_ADMINS_LOADING = "TOGGLE_ADMINS_LOADING";
export const LIST_ADMIN = "LIST_ADMIN";
export const SET_CURRENT_ADMIN = "SET_CURRENT_ADMIN";
export const UPDATE_ADMIN = "UPDATE_ADMIN";
export const CREATE_ADMIN = "CREATE_ADMIN";
export const DELETE_ADMIN = "DELETE_ADMIN";
// product options
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const LIST_PRODUCTS = "LIST_PRODUCTS";
export const TOGGLE_PRODUCT_LOADING = "TOGGLE_PRODUCT_LOADING";
export const TOGGLE_PRODUCTS_LOADING = "TOGGLE_PRODUCTS_LOADING";

// category options
export const TOGGLE_CATEGORY_LOADING = "TOGGLE_CATEGORY_LOADING";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CHILD_CATES = "GET_CHILD_CATES";

export const TOGGLE_CART = "TOGGLE_CART";
export const TOGGLE_WISHLIST = "TOGGLE_WISHLIST";
export const TOGGLE_SEARCH = "TOGGLE_SEARCH";

export const SET_CART  = "SET_CART";
export const SET_WISHLIST  = "SET_WISHLIST";
export const SET_TOTAL = "SET_TOTAL";

export const GET_SHIPPING = "GET_SHIPPING";
export const GET_PAYMENT = "GET_PAYMENT";
export const TOGGLE_CHECKOUT_LOADING = "TOGGLE_CHECKOUT_LOADING";


