export const SET_ERRORS = "SET_ERRORS";

// customer options
export const TOGGLE_CUSTOMER_LOADING = "TOGGLE_CUSTOMER_LOADING";
export const SET_CURRENT_CUSTOMER = "SET_CURRENT_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

// customer options
export const TOGGLE_ADMIN_LOADING = "TOGGLE_ADMIN_LOADING";
export const TOGGLE_ADMINER_LOADING = "TOGGLE_ADMINER_LOADING";
export const SET_CURRENT_ADMIN = "SET_CURRENT_ADMIN";
export const UPDATE_ADMIN = "UPDATE_ADMIN";

// product options
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const LIST_PRODUCTS = "LIST_PRODUCTS";
export const TOGGLE_PRODUCT_LOADING = "PRODUCT_LOADING";
export const TOGGLE_PRODUCTS_LOADING = "PRODUCTS_LOADING";

// category options
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const CHILDREN_CATE_PRODUCTS = "CHILDREN_CATE_PRODUCTS";
